name: "Shared setup"
description: "Set up Node.js with PNPM"

inputs:
  app_dir:
    description: "The folder where the app is located"
    required: true

runs:
  using: composite
  steps:
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: pnpm
        cache-dependency-path: ${{ inputs.app_dir }}

    - name: Install PNPM
      uses: pnpm/action-setup@v4
      with:
        version: 9.4.0
    - name: Install deps
      run: pnpm install
      shell: bash
      working-directory: ${{ inputs.app_dir }}
    - name: Print parameters
      shell: bash
      run: echo ${{ inputs.app_dir }}
