name: API Check

on:
  workflow_call:
    inputs:
      enabled:
        description: "Skip the workflow steps"
        default: "false"
        type: "string"
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    if: ${{ inputs.enabled == 'true' }}
    steps:
      - name: Lint
        run: |
          echo "## API Linting OK! :white_check_mark:" >> $GITHUB_STEP_SUMMARY
