name: API Check

on:
  workflow_call:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Lint
        run: |
          echo "## API Linting OK! :white_check_mark:" >> $GITHUB_STEP_SUMMARY
