name: Check

on:
  workflow_call:

jobs:
  check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
      - name: Set up Node.js and PNPM
        uses: ./.github/shared-actions/setup-nodejs
        with:
          app_dir: "app"
      - name: Dummy check
        run: echo 'Check OK!'
