name: Check

on:
  workflow_call:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
      - name: Set up Node.js and PNPM
        uses: ./.github/shared-actions/setup-nodejs
      - name: Dummy check
        run: echo 'Check OK!'
