name: Dummy

on:
  workflow_call:
  workflow_dispatch:

jobs:
  dummy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: remix-app
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
      - run: echo 'Dummy job OK!'
