name: CI Pipeline

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  # Detect what files have changed in the whole PR, to trigger only the necessary checks
  changes:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            api:
              - 'api/**'
              - 'packages/**'
            web:
              - 'web/**'
              - 'packages/**'

    outputs:
      api: ${{ steps.filter.outputs.api }}
      web: ${{ steps.filter.outputs.web }}

  # API checks
  main-api-check:
    needs: changes
    uses: ./.github/workflows/api-check.yml
    with:
      enabled: ${{ needs.changes.outputs.api == 'true' }}

  # Web checks
  main-web-check:
    needs: changes
    uses: ./.github/workflows/web-check.yml
    with:
      enabled: ${{ needs.changes.outputs.web == 'true' }}
