name: CI Pipeline

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  # Detect what files have changed in the whole PR, to trigger only the necessary checks
  changes:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            api:
              - 'api/**'
              - 'packages/**'
            web:
              - 'web/**'
              - 'packages/**'

    outputs:
      api: ${{ steps.filter.outputs.api }}
      web: ${{ steps.filter.outputs.web }}

  main-api-check:
    needs: changes
    runs-on: ubuntu-latest
    steps:
      - name: Run API checks
        if: ${{ needs.changes.outputs.api == 'true' }}
        uses: ./.github/workflows/api-check.yml
      - name: Mark as successful if skipped
        if: ${{ needs.changes.outputs.api == 'false' }}
        run: echo "API checks skipped"

  main-web-check:
    needs: changes
    runs-on: ubuntu-latest
    steps:
      - name: Run Web checks
        if: ${{ needs.changes.outputs.web == 'true' }}
        uses: ./.github/workflows/web-check.yml
      - name: Mark as successful if skipped
        if: ${{ needs.changes.outputs.web == 'false' }}
        run: echo "Web checks skipped"
