name: CI Pipeline

on:
  push:
  pull_request:
    branches:
      - $default-branch

env:
  APP_DIRECTORY: ./app

jobs:
  check:
    uses: ./.github/workflows/check.yml

  dummy:
    uses: ./.github/workflows/dummy.yml
