name: CI Pipeline

on:
  push:
  pull_request:
    branches:
      - $default-branch

env:
  APP_DIRECTORY: ./remix-app

jobs:
  check:
    uses: ./.github/workflows/check.yml

  dummy:
    uses: ./.github/workflows/dummy.yml

  deploy-production:
    needs: check
    if: startsWith(github.ref, 'refs/tags/')
    uses: ./.github/workflows/deploy-production.yml
