name: Web Check

on:
  workflow_call:
    inputs:
      enabled:
        description: "Skip the workflow steps"
        default: false
        type: "boolean"
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Skip if not needed
        if: ${{ !inputs.enabled }}
        run: echo "Skip web check"

      - name: Code Checkout
        if: ${{ inputs.enabled }}
        run: |
          echo "Code Checkout"
      - name: Lint
        if: ${{ inputs.enabled }}
        run: |
          echo "## Web Lint OK! :white_check_mark:" >> $GITHUB_STEP_SUMMARY
      - name: Test
        if: ${{ inputs.enabled }}
        run: |
          echo "## API Lint OK! :white_check_mark:" >> $GITHUB_STEP_SUMMARY
