name: Web Check

on:
  workflow_call:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Lint
        run: |
          echo "## Web Linting OK! :white_check_mark:" >> $GITHUB_STEP_SUMMARY
      - name: Test
        run: |
          echo "## Web Test OK! :white_check_mark:" >> $GITHUB_STEP_SUMMARY
