name: Web Check

on:
  workflow_call:
    inputs:
      enabled:
        description: "Skip the workflow steps"
        default: "false"
        type: "string"
  workflow_dispatch:

jobs:
  check:
    if: ${{ inputs.enabled == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Lint
        run: |
          echo "## Web Linting OK! :white_check_mark:" >> $GITHUB_STEP_SUMMARY
      - name: Test
        run: |
          echo "## Web Linting OK! :white_check_mark:" >> $GITHUB_STEP_SUMMARY

  skip:
    if: ${{ inputs.enabled == 'false' }}
    runs-on: ubuntu-latest
    steps:
      - name: Skip
        run: echo "Skipping checks"
